services:
  db:
    image: postgres:latest
    container_name: rental-movies-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: rental-movies
    ports:
      - "5540:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: 
    driver: local
